import type { Metadata } from "next"
import "./globals.css"
import localFont from "next/font/local"
import Navbar from "../components/navbar/navbar"
import Head from "next/head"

const poppins = localFont({
  src: "../../public/fonts/Poppins-Regular.ttf",
  display: "swap",
  variable: "--font-poppins",
})
const opensauce = localFont({
  src: "../../public/fonts/OpenSauceOne-Regular.ttf",
  variable: "--font-opensauce",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <title>HuHu24 leirisovellus</title>
        <meta
          name="description"
          content="HuHu 2024 partioleirin puhelinsovellus"
        />
        <link rel="shortcut icon" href="/public/favico.ico" />
      </Head>
      <body className={`${opensauce.variable} ${poppins.variable}`}>
        {children}
        <Navbar />
      </body>
    </html>
  )
}
